/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Gabriel
 */

import conexoes.MySQL;
import hs.hs;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import objetos.Produto;


public class Loja extends javax.swing.JFrame {
    
    DefaultListModel listModel = new DefaultListModel();
    MySQL conectar = new MySQL(); //acessar os métodos de conexao com o banco
    Produto novoProduto = new Produto(); //acessar os atributos da classe cliente
    hs HS = new hs();

    
    int numeroCasas = 0;
    
    /**
     * Creates new form Loja
     */
    public Loja() {
        initComponents();
        setResizable(false);
        casasLength();
        buscarProduto(novoProduto, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    
    private void casasLength(){
         
        this.conectar.conectaBanco();
                  
        try {
            this.conectar.executarSQL(
                   "select count(*) from listaCasas;"
                  
            );
            
            while(this.conectar.getResultSet().next()){               
                
                try{
                    numeroCasas = Integer.parseInt(this.conectar.getResultSet().getString(1));
                    System.out.println(numeroCasas);
                    inicializaListaCasas(numeroCasas);
                }
                catch (NumberFormatException ex){
                    ex.printStackTrace();
                }
         
            }

            } catch (Exception e) {            
                JOptionPane.showMessageDialog(null, "Erro ao processar o pedido");

            }finally{

                this.conectar.fechaBanco();   
            }               
    }  

    private void inicializaListaCasas(int quantidade)
    {
    
        for(int i = 0; i <= quantidade; i++)
        
        {
            this.conectar.conectaBanco();  
                
        try {
            this.conectar.executarSQL(
                        "select * from listaCasas where id =" + i + ";"
            );
            
            while(this.conectar.getResultSet().next()){               

                    
            listModel.addElement(this.conectar.getResultSet().getString(2));
                
           }
            
           if(novoProduto.getNome_casa() == ""){
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
           }
           
        } catch (Exception e) {            
            System.out.println("Erro ao consultar produto " +  e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
            
        }finally{
            atualizaCampos(novoProduto);

            this.conectar.fechaBanco();   
        }               
        }
        
    }
    
     private void buscarProduto(Produto novoProduto, int id){
         
        this.conectar.conectaBanco();  
                
        try {
            this.conectar.executarSQL(
                        "select * from listaCasas where id =" + id + ";"
            );
            
            while(this.conectar.getResultSet().next()){            
                novoProduto.setNome_casa(this.conectar.getResultSet().getString(2));
                novoProduto.setCasa_valor(this.conectar.getResultSet().getInt(8));
                novoProduto.setCasa_cidade(this.conectar.getResultSet().getString(3));
                novoProduto.setCasa_endereco(this.conectar.getResultSet().getString(4));
                novoProduto.setCasa_numero(this.conectar.getResultSet().getInt(5));
                novoProduto.setCasa_quartos(this.conectar.getResultSet().getInt(6));
                novoProduto.setCasa_banheiros(this.conectar.getResultSet().getInt(7));
                novoProduto.setCasa_piscina(this.conectar.getResultSet().getString(10));
                novoProduto.setCasa_churrasqueira(this.conectar.getResultSet().getString(11));
                novoProduto.setCasa_dono(this.conectar.getResultSet().getString(9));

           }
            
           if(novoProduto.getNome_casa() == ""){
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
           }
           
        } catch (Exception e) {            
            System.out.println("Erro ao consultar produto " +  e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar produto");
            
        }finally{
                atualizaCampos(novoProduto);

            this.conectar.fechaBanco();   
        }               
    }    
    
    
    
   private void atualizaCampos(Produto novoProduto)
    {
        varNome.setText(novoProduto.getNome_casa());
        varCidade.setText(novoProduto.getCasa_cidade());
        varEndereco.setText(novoProduto.getCasa_endereco());
        varNumero.setText(String.format("%d",novoProduto.getCasa_numero()));
        varQuartos.setText(String.format("%d", novoProduto.getCasa_quartos()));
        varBanheiro.setText(String.format("%d", novoProduto.getCasa_banheiros()));
        varPiscina.setText(novoProduto.getCasa_piscina());
        varChurrasqueira.setText(novoProduto.getCasa_churrasqueira());
        varDono.setText(novoProduto.getCasa_dono());
        varValor.setText( String.format("%f", novoProduto.getCasa_valor() ) );
        //varImagem.setIcon("");
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_casas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        varCidade = new javax.swing.JLabel();
        varNome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        varEndereco = new javax.swing.JLabel();
        varNumero = new javax.swing.JLabel();
        varQuartos = new javax.swing.JLabel();
        varBanheiro = new javax.swing.JLabel();
        varPiscina = new javax.swing.JLabel();
        varChurrasqueira = new javax.swing.JLabel();
        varValor = new javax.swing.JLabel();
        varDono = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        varImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 30, 49));

        Lista_casas.setModel(listModel);
        Lista_casas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lista_casasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Lista_casas);

        jLabel1.setText("Nome:");

        jLabel2.setText("Cidade:");

        varCidade.setText("jLabel3");

        varNome.setText("Nome");

        jLabel5.setText("Endereço:");

        jLabel6.setText("Número:");

        jLabel8.setText("Dono:");

        jLabel9.setText("Quartos:");

        jLabel10.setText("Banheiros:");

        jLabel11.setText("Piscina:");

        jLabel12.setText("Churrasqueira:");

        jLabel13.setText("Valor:");

        varEndereco.setText("jLabel14");

        varNumero.setText("jLabel15");

        varQuartos.setText("jLabel16");

        varBanheiro.setText("jLabel17");

        varPiscina.setText("jLabel18");

        varChurrasqueira.setText("jLabel19");

        varValor.setText("jLabel20");

        varDono.setText("jLabel21");

        jButton1.setText("Sair");

        jButton2.setText("Alugar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        varImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/350.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varDono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varCidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varQuartos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varBanheiro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varPiscina))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                .addComponent(varChurrasqueira))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varValor)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(varImagem)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(varNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(varCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(varEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(varNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(varQuartos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(varBanheiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(varPiscina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(varChurrasqueira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(varDono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(varValor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(varImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lista_casasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lista_casasMouseClicked
        buscarProduto(novoProduto, Lista_casas.getSelectedIndex()+1);
    }//GEN-LAST:event_Lista_casasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista_casas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel varBanheiro;
    private javax.swing.JLabel varChurrasqueira;
    private javax.swing.JLabel varCidade;
    private javax.swing.JLabel varDono;
    private javax.swing.JLabel varEndereco;
    private javax.swing.JLabel varImagem;
    private javax.swing.JLabel varNome;
    private javax.swing.JLabel varNumero;
    private javax.swing.JLabel varPiscina;
    private javax.swing.JLabel varQuartos;
    private javax.swing.JLabel varValor;
    // End of variables declaration//GEN-END:variables
}
